### ISSUE TITLE
Credit to dragonfire535/xiao

### ISSUE THREAD

**Issue by dragonfire535** [Anish-Shobith/discord.js-canvas#2]
This repository is basically a strangely formatted copy of [my repo's CanvasUtil class](https://github.com/dragonfire535/xiao/blob/master/util/Canvas.js). Please properly follow the [GPL license](https://github.com/dragonfire535/xiao/blob/master/LICENSE.md).

**Comment by Anish-Shobith** [comment]
Sure!!!
